import localFont from "next/font/local";
import "./globals.css";

const enzyme = localFont({
  src: "./fonts/Enzyme.otf",
  weight: "100 200 300 400 500",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${enzyme.className} antialiased relative`}>
        {children}
      </body>
    </html>
  );
}
